name: e_commerce
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  photo_view: ^0.14.0
  animated_text_kit: ^4.2.2
  flutter_native_splash: ^2.2.0
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  http: ^0.13.4
  get_it: ^7.6.0
  auto_route: ^7.2.0
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  badges: ^3.1.1


flutter_native_splash:
  color: "#2596be"
  image: images/OLX.png
  android: true
  ios: true



dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  freezed: ^2.3.2
  injectable_generator: ^2.1.6
  auto_route_generator: ^7.2.0
  shared_preferences: ^2.2.0



  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/


